package handlers

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"net/http"
	"regexp"
	"strings"
	"testing"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/kubestellar/console/pkg/mcp"
)

func TestOrbitCadenceHoursComplete(t *testing.T) {
	expected := map[string]float64{
		"daily":   24,
		"weekly":  168,
		"monthly": 720,
	}
	for cadence, hours := range expected {
		got, ok := orbitCadenceHours[cadence]
		if !ok {
			t.Errorf("missing cadence %q in orbitCadenceHours", cadence)
			continue
		}
		if got != hours {
			t.Errorf("orbitCadenceHours[%q] = %v, want %v", cadence, got, hours)
		}
	}
}

func TestIsDue(t *testing.T) {
	now := time.Now().UTC()

	tests := []struct {
		name      string
		cadence   string
		lastRunAt string
		wantDue   bool
	}{
		{
			name:      "daily mission run 25h ago is due",
			cadence:   "daily",
			lastRunAt: now.Add(-25 * time.Hour).Format(time.RFC3339),
			wantDue:   true,
		},
		{
			name:      "daily mission run 23h ago is not due",
			cadence:   "daily",
			lastRunAt: now.Add(-23 * time.Hour).Format(time.RFC3339),
			wantDue:   false,
		},
		{
			name:      "weekly mission run 8 days ago is due",
			cadence:   "weekly",
			lastRunAt: now.Add(-8 * 24 * time.Hour).Format(time.RFC3339),
			wantDue:   true,
		},
		{
			name:      "weekly mission run 6 days ago is not due",
			cadence:   "weekly",
			lastRunAt: now.Add(-6 * 24 * time.Hour).Format(time.RFC3339),
			wantDue:   false,
		},
		{
			name:      "monthly mission run 31 days ago is due",
			cadence:   "monthly",
			lastRunAt: now.Add(-31 * 24 * time.Hour).Format(time.RFC3339),
			wantDue:   true,
		},
		{
			name:      "never-run mission is due",
			cadence:   "weekly",
			lastRunAt: "",
			wantDue:   true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			m := &OrbitMission{
				Cadence: tt.cadence,
				AutoRun: true,
			}
			if tt.lastRunAt != "" {
				m.LastRunAt = &tt.lastRunAt
			}

			cadenceHrs, ok := orbitCadenceHours[m.Cadence]
			if !ok {
				t.Fatalf("unknown cadence %q", m.Cadence)
			}

			isDue := false
			if m.LastRunAt == nil || *m.LastRunAt == "" {
				isDue = true
			} else {
				lastRun, err := time.Parse(time.RFC3339, *m.LastRunAt)
				if err != nil {
					t.Fatalf("invalid lastRunAt: %v", err)
				}
				elapsed := time.Since(lastRun).Hours()
				isDue = elapsed >= cadenceHrs
			}

			if isDue != tt.wantDue {
				t.Errorf("isDue = %v, want %v", isDue, tt.wantDue)
			}
		})
	}
}

// TestCreateMission_AutoGeneratedID verifies that creating a mission without
// an explicit ID produces one with the expected shape:
//
//	orbit-<14-digit-datetime>.<3-digit-ms>-<4-hex-suffix>
//
// This guards against regressions in generateOrbitSuffix (#7855 / #7815) — in
// particular it prevents the broken fallback `time.Now().Format("0000")` which
// would emit the literal string "0000" instead of random hex.
func TestCreateMission_AutoGeneratedID(t *testing.T) {
	// Write to a temp dir so we don't touch the real data directory.
	h := NewOrbitHandler(t.TempDir(), nil)
	app := fiber.New()
	app.Post("/missions", h.CreateMission)

	payload, err := json.Marshal(map[string]any{
		"title":     "Test Mission",
		"orbitType": "health-check",
		"cadence":   "daily",
	})
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}

	req, err := http.NewRequest(http.MethodPost, "/missions", bytes.NewReader(payload))
	if err != nil {
		t.Fatalf("new request: %v", err)
	}
	req.Header.Set("Content-Type", "application/json")

	// fiberTestTimeoutMS: test-local timeout (ms) for the in-process Fiber test.
	const fiberTestTimeoutMS = 5000
	resp, err := app.Test(req, fiberTestTimeoutMS)
	if err != nil {
		t.Fatalf("app.Test: %v", err)
	}
	if resp.StatusCode != http.StatusCreated {
		body, _ := io.ReadAll(resp.Body)
		t.Fatalf("status = %d, want 201; body=%s", resp.StatusCode, string(body))
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		t.Fatalf("read body: %v", err)
	}
	var got OrbitMission
	if err := json.Unmarshal(body, &got); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}

	// Expected format: orbit-YYYYMMDDHHMMSS.mmm-xxxx (xxxx = hex)
	idPattern := regexp.MustCompile(`^orbit-\d{14}\.\d{3}-[0-9a-f]{4}$`)
	if !idPattern.MatchString(got.ID) {
		t.Errorf("ID = %q, want match %s", got.ID, idPattern)
	}

	// Sanity: the suffix must not be the literal "0000" fallback from the old
	// broken time.Format("0000") behavior. Given crypto/rand, collision with
	// "0000" is 1/65536 — acceptable for a single test invocation.
	if len(got.ID) >= 4 && got.ID[len(got.ID)-4:] == "0000" {
		t.Errorf("ID suffix is literal 0000, suggests broken random fallback: %q", got.ID)
	}
}

// TestGenerateOrbitSuffix_ShapeAndVariability verifies the suffix is always
// 4 lowercase hex characters and that successive calls produce different
// values (probabilistically — 1/65536 collision chance per call).
func TestGenerateOrbitSuffix_ShapeAndVariability(t *testing.T) {
	const suffixHexChars = 4
	pat := regexp.MustCompile(`^[0-9a-f]{4}$`)
	seen := make(map[string]struct{})
	// sampleSize: enough calls that total collision across all samples is
	// statistically negligible (1 - (1-1/65536)^N stays tiny for N=16).
	const sampleSize = 16
	for i := 0; i < sampleSize; i++ {
		s := generateOrbitSuffix()
		if len(s) != suffixHexChars {
			t.Errorf("suffix %q length = %d, want %d", s, len(s), suffixHexChars)
		}
		if !pat.MatchString(s) {
			t.Errorf("suffix %q does not match %s", s, pat)
		}
		seen[s] = struct{}{}
	}
	if len(seen) < 2 {
		t.Errorf("generateOrbitSuffix produced the same value %d times — not random", sampleSize)
	}
}

func TestOrbitMissionSerialization(t *testing.T) {
	m := &OrbitMission{
		ID:          "test-1",
		Title:       "Health Check",
		Description: "Check pod health",
		OrbitType:   "health-check",
		Cadence:     "weekly",
		AutoRun:     true,
		Clusters:    []string{"cluster-a"},
		Steps: []OrbitStep{
			{Title: "Check pods", Description: "Verify all pods running"},
		},
		CreatedAt: time.Now().UTC().Format(time.RFC3339),
		History:   []OrbitRunRecord{},
	}

	if m.ID != "test-1" {
		t.Errorf("ID = %q, want %q", m.ID, "test-1")
	}
	if m.OrbitType != "health-check" {
		t.Errorf("OrbitType = %q, want %q", m.OrbitType, "health-check")
	}
	if !m.AutoRun {
		t.Error("AutoRun should be true")
	}
	if len(m.Steps) != 1 {
		t.Errorf("Steps len = %d, want 1", len(m.Steps))
	}
	if m.LastRunAt != nil {
		t.Error("LastRunAt should be nil for new mission")
	}
}

type orbitTestExecutor struct {
	tools   []mcp.Tool
	results map[string]*mcp.CallToolResult
	errors  map[string]error
	calls   []orbitTestCall
}

type orbitTestCall struct {
	name string
	args map[string]interface{}
}

func (e *orbitTestExecutor) GetOpsTools() []mcp.Tool {
	return e.tools
}

func (e *orbitTestExecutor) CallOpsTool(_ context.Context, name string, args map[string]interface{}) (*mcp.CallToolResult, error) {
	e.calls = append(e.calls, orbitTestCall{name: name, args: orbitCloneArgs(args)})
	if err := e.errors[name]; err != nil {
		return nil, err
	}
	if result, ok := e.results[name]; ok {
		return result, nil
	}
	return &mcp.CallToolResult{Content: []mcp.ContentItem{{Type: "text", Text: "ok"}}}, nil
}

func makeOrbitTestTool(name string, required ...string) mcp.Tool {
	properties := map[string]mcp.Property{
		"cluster": {Type: "string"},
	}
	return mcp.Tool{
		Name: name,
		InputSchema: mcp.InputSchema{
			Type:       "object",
			Properties: properties,
			Required:   required,
		},
	}
}

func TestRunMissionReturnsSkippedWithoutExecutor(t *testing.T) {
	h := NewOrbitHandler(t.TempDir(), nil)
	h.missions["orbit-skip"] = &OrbitMission{
		ID:        "orbit-skip",
		Title:     "Health Check",
		OrbitType: "health-check",
		Cadence:   "daily",
		Steps: []OrbitStep{{
			Title:       "Check pod health",
			Description: "Verify all pods are healthy.",
		}},
		History: []OrbitRunRecord{},
	}

	app := fiber.New()
	app.Post("/missions/:id/run", h.RunMission)

	req, err := http.NewRequest(http.MethodPost, "/missions/orbit-skip/run", nil)
	if err != nil {
		t.Fatalf("new request: %v", err)
	}
	const fiberTestTimeoutMS = 5000
	resp, err := app.Test(req, fiberTestTimeoutMS)
	if err != nil {
		t.Fatalf("app.Test: %v", err)
	}
	defer resp.Body.Close()

	var got orbitMissionExecution
	if err := json.NewDecoder(resp.Body).Decode(&got); err != nil {
		t.Fatalf("decode response: %v", err)
	}
	if got.MissionID != "orbit-skip" {
		t.Fatalf("missionId = %q, want orbit-skip", got.MissionID)
	}
	if got.RunAt == "" {
		t.Fatal("runAt should be populated")
	}
	if got.Result != "skipped" {
		t.Fatalf("result = %q, want skipped", got.Result)
	}
	if got.Summary != "No executor configured" {
		t.Fatalf("summary = %q, want exact skip summary", got.Summary)
	}
	if got.ExecutionTime == "" {
		t.Fatal("executionTime should be populated")
	}
	if h.missions["orbit-skip"].LastRunResult == nil || *h.missions["orbit-skip"].LastRunResult != "skipped" {
		t.Fatalf("LastRunResult = %v, want skipped", h.missions["orbit-skip"].LastRunResult)
	}
	if len(h.missions["orbit-skip"].History) != 1 || h.missions["orbit-skip"].History[0].Summary != "No executor configured" {
		t.Fatalf("history summary = %+v, want persisted skip summary", h.missions["orbit-skip"].History)
	}
}

func TestRunMissionExecutesStepsViaMCP(t *testing.T) {
	executor := &orbitTestExecutor{
		tools: []mcp.Tool{makeOrbitTestTool("get_cluster_health")},
		results: map[string]*mcp.CallToolResult{
			"get_cluster_health": {
				Content: []mcp.ContentItem{{Type: "text", Text: "healthy"}},
			},
		},
	}
	h := NewOrbitHandler(t.TempDir(), executor)
	h.missions["orbit-success"] = &OrbitMission{
		ID:        "orbit-success",
		Title:     "Health Check",
		OrbitType: "health-check",
		Cadence:   "daily",
		Clusters:  []string{"cluster-a"},
		Steps: []OrbitStep{{
			Title:       "Check cluster health",
			Description: "Verify cluster health is good.",
		}},
		History: []OrbitRunRecord{},
	}

	app := fiber.New()
	app.Post("/missions/:id/run", h.RunMission)

	req, err := http.NewRequest(http.MethodPost, "/missions/orbit-success/run", nil)
	if err != nil {
		t.Fatalf("new request: %v", err)
	}
	const fiberTestTimeoutMS = 5000
	resp, err := app.Test(req, fiberTestTimeoutMS)
	if err != nil {
		t.Fatalf("app.Test: %v", err)
	}
	defer resp.Body.Close()

	var got orbitMissionExecution
	if err := json.NewDecoder(resp.Body).Decode(&got); err != nil {
		t.Fatalf("decode response: %v", err)
	}
	if got.MissionID != "orbit-success" {
		t.Fatalf("missionId = %q, want orbit-success", got.MissionID)
	}
	if got.RunAt == "" {
		t.Fatal("runAt should be populated")
	}
	if got.Result != "success" {
		t.Fatalf("result = %q, want success", got.Result)
	}
	if !strings.Contains(got.Summary, "Executed 1/1 orbit steps via MCP") {
		t.Fatalf("summary = %q, want execution summary", got.Summary)
	}
	if got.ExecutionTime == "" {
		t.Fatal("executionTime should be populated")
	}
	if len(executor.calls) != 1 {
		t.Fatalf("calls = %d, want 1", len(executor.calls))
	}
	if cluster := executor.calls[0].args["cluster"]; cluster != "cluster-a" {
		t.Fatalf("cluster arg = %v, want cluster-a", cluster)
	}
	if len(h.missions["orbit-success"].History) != 1 || !strings.Contains(h.missions["orbit-success"].History[0].Summary, "Executed 1/1 orbit steps via MCP") {
		t.Fatalf("history = %+v, want stored success summary", h.missions["orbit-success"].History)
	}
}

func TestRunMissionFailsWhenExecutorHasNoOpsTools(t *testing.T) {
	executor := &orbitTestExecutor{}
	h := NewOrbitHandler(t.TempDir(), executor)
	h.missions["orbit-no-tools"] = &OrbitMission{
		ID:        "orbit-no-tools",
		Title:     "Health Check",
		OrbitType: "health-check",
		Cadence:   "daily",
		Steps: []OrbitStep{{
			Title:       "Check cluster health",
			Description: "Verify cluster health is good.",
		}},
		History: []OrbitRunRecord{},
	}

	app := fiber.New()
	app.Post("/missions/:id/run", h.RunMission)

	req, err := http.NewRequest(http.MethodPost, "/missions/orbit-no-tools/run", nil)
	if err != nil {
		t.Fatalf("new request: %v", err)
	}
	const fiberTestTimeoutMS = 5000
	resp, err := app.Test(req, fiberTestTimeoutMS)
	if err != nil {
		t.Fatalf("app.Test: %v", err)
	}
	defer resp.Body.Close()

	var got orbitMissionExecution
	if err := json.NewDecoder(resp.Body).Decode(&got); err != nil {
		t.Fatalf("decode response: %v", err)
	}
	if got.Result != "failed" {
		t.Fatalf("result = %q, want failed", got.Result)
	}
	if !strings.Contains(got.Summary, "no available ops tools") {
		t.Fatalf("summary = %q, want executor tool failure", got.Summary)
	}
}

func TestCheckDueMissionsStoresFailedExecution(t *testing.T) {
	executor := &orbitTestExecutor{
		tools: []mcp.Tool{makeOrbitTestTool("get_events")},
		results: map[string]*mcp.CallToolResult{
			"get_events": {
				IsError: true,
				Content: []mcp.ContentItem{{Type: "text", Text: "backup jobs unavailable"}},
			},
		},
	}
	h := NewOrbitHandler(t.TempDir(), executor)
	h.missions["orbit-failed"] = &OrbitMission{
		ID:        "orbit-failed",
		Title:     "Backup Verification",
		OrbitType: "backup-verification",
		Cadence:   "daily",
		AutoRun:   true,
		Steps: []OrbitStep{{
			Title:       "Check backup job status",
			Description: "Verify recent backup jobs completed successfully.",
		}},
		History: []OrbitRunRecord{},
	}

	h.checkDueMissions()

	mission := h.missions["orbit-failed"]
	if mission.LastRunResult == nil || *mission.LastRunResult != "failed" {
		t.Fatalf("LastRunResult = %v, want failed", mission.LastRunResult)
	}
	if len(mission.History) != 1 {
		t.Fatalf("history len = %d, want 1", len(mission.History))
	}
	if !strings.Contains(mission.History[0].Summary, "backup jobs unavailable") {
		t.Fatalf("summary = %q, want tool failure", mission.History[0].Summary)
	}
}
